# Should have a step to deploy to gh-pages

name: build-test
on:
  push:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - run: python --version
      - run: pip install -r requirements.txt
      - name: Make all
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: "./repositories/artifacts"
